website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Poll(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    description = db.Column(db.String(2000))
    question = db.Column(db.String(200))
    option_1 = db.Column(db.String(150))
    option_2 = db.Column(db.String(150))
    option_3 = db.Column(db.String(150))
    option_4 = db.Column(db.String(150))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    user_name = db.Column(db.String(100), unique=True)
    polls = db.relationship("Poll")

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager



db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "key"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    db.init_app(app)
    
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User, Poll

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists("website/" + DB_NAME):
        with app.app_context():
            db.create_all()
            print("Database created!")

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user



auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect password, try again", category="error")
        else:
            flash("Email does not exist.", category="error") 
    return render_template("login.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        user_name = request.form.get("userName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exist.", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 3 characters.", category="error")
        elif len(user_name) < 2:
            flash("User Name must be greater than 1 character.", category="error")
        elif password1 != password2:
            flash("Passwords don't match.", category="error")
        elif len(password1) < 7:
            flash("Email must be at least 7 characters.", category="error")
        else:
            new_user = User(email=email, user_name=user_name, password=generate_password_hash(password1, method="sha256"))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category="success")
            return redirect(url_for("views.home"))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Poll, User
from . import db
import json

views = Blueprint("views", __name__)

@views.route("/", methods=["GET", "POST"])
@login_required
def home():
    
    return render_template("home.html", user=current_user)

@views.route("/delete-poll", methods=["POST"])
def delete_poll():
    poll = json.loads(request.data)
    pollId = poll["pollId"]
    poll = Poll.query.get(pollId)
    if poll:
       if poll.user_id == current_user.id:
           db.session.delete(poll) 
           db.session.commit()
    
    return jsonify({})

@views.route("/vote", methods=["GET", "POST"])
@login_required
def vote():
    polls = Poll.query.all()
    user_names = {}  # Create a dictionary to store user names for each poll
    for poll in polls:
        user = User.query.get(poll.user_id)

        if user:
            user_names[poll.id] = user.user_name

    
    return render_template("vote.html", user=current_user, polls=polls, user_names=user_names)

@views.route("create", methods=["GET", "POST"])
@login_required
def create():
    if request.method == "POST":

        title = request.form.get("poll-title")
        description = request.form.get("poll-description")

        question = request.form.get("question")
        option_1 = request.form.get("option_1")
        option_2 = request.form.get("option_2")
        option_3 = request.form.get("option_3")
        option_4 = request.form.get("option_4")

        if len(question) < 1:
            flash("Question is too short.", category="error")
        elif not(option_1):
            flash("Option 1 and Option 2 are required.", category="error")
        elif not(option_2):
            flash("Option 1 and Option 2 are required.", category="error")
        elif len(title) > 25:
            flash("The title is too long", category="error")
        elif len(description) > 250:
            flash("The description is too long", category="error")
        else:
            new_poll = Poll(title=title,
                            description=description,
                            question=question, 
                            option_1 = option_1, 
                            option_2 = option_2, 
                            option_3 = option_3, 
                            option_4 = option_4,
                            user_id=current_user.id)
            db.session.add(new_poll)
            db.session.commit()
            flash("Poll Created!", category="success")
            
    return render_template("create.html", user=current_user)
        

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Home{% endblock %}</title>
        <!-- CSS -->
        <!-- <link rel="stylesheet" href="styles.css"> -->
        <!-- Bootstrap -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link"id="home" href="/">Home</a>
                    <a class="nav-item nav-link"id="logout" href="/logout">Logout</a>
                    <a class="nav-item nav-link"id="create" href="/create">Create</a>
                    <a class="nav-item nav-link"id="vote" href="/vote">Vote</a>
                    {% else %}
                    <a class="nav-item nav-link"id="login" href="/login">Login</a>
                    <a class="nav-item nav-link"id="signUp" href="/sign-up">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages =  get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="flash_container">
            {% for category, message in messages %}
            {% if category == "error" %}
            <div class="alert alert-danger alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <div class="container">
            <br>
            <br>
            <br>
            {% block content %}
            {% endblock %}
        </div>
        <!-- Bootstrap -->
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
        <!-- Javascript -->
        <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
    </body>
</html>

website/templates/create.html
{% extends "base.html" %}
{% block title %}Create Polls{% endblock %}

{% block content %}
<!-- form element -->
<section class="create-polls">
    <h1 align="center">Create Polls</h1>

    <form align="center" method="POST" id="pollForm" class="create_form">
         
        <!-- <p>[All Image File are <strong>optional</strong>]</p> -->
        <div class="poll-information">
            <h4><strong>Title</strong> (optional)</h4>
            <input type="text"name="poll-title" placeholder="Title of the poll">
            <!-- <h4>Add image (optional)</h4>
            <input type="file" class="info__img" name="info_img"> -->
            <h4>Description (optional)</h4>
            <textarea class="poll-description" name="poll-description" rows="4" columns="50"></textarea>
        </div>
        <div class="create">

            <h4 class="build__question">Choose your <strong>Question</strong></h4>
            <input type="text" name="question" placeholder="What's your favourite food?">
        
            <div class="create-option">
                <p class="build__options"><strong>Option 1:</strong></p>
                <!-- <input type="file" class="option__img"> -->
                <input type="text" name="option_1" placeholder="Pizza">
            </div>
            
            <div class="create-option">
                <p class="build__options"><strong>Option 2:</strong></p>
                <!-- <input type="file" class="option__img"> -->
                <input type="text" name="option_2" placeholder="Sushi">
            </div>
            
            <div class="create-option">
                <p class="build__options"><strong>Option 3:</strong></p>
                <!-- <input type="file" class="option__img" > -->
                <input type="text" name="option_3" placeholder="Hamburger">
            </div>
            
            <div class="create-option">
                <p class="build__options"><strong>Option 4:</strong></p>
                <!-- <input type="file" class="option__img"> -->
                <input type="text" name="option_4" placeholder="Other">
            </div>
        </div>
        
        <div align="center">
            <button type="submit" class="create-poll-btn">Create</button>
        </div>
    </form>
</section>
{% endblock%}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<!-- Create Polls -->
<section class="create-section" id="create-section" align="center">
    <h2><strong>Create</strong> Polls</h2>
    <p>Create a poll</p>
    <button class="create-section__button"><a href="{{ url_for('views.create') }}">Create</a></button>
</section>

<!-- Vote polls -->
<section class="vote-section" id="vote-section" align="center">
    <h2><strong>Vote</strong> Polls</h2>
    <p>Vote all existing polls</p>
    <button class="vote-section__button"><a href="{{ url_for('views.vote') }}">Go</a></button>
</section>

<section class="my-polls">
    <h1 align="center">My Polls</h1>
    <!-- Search Bar -->
    <br>
    <div class="search-bar">
        <input type="text" class="search-input" id="pollSearch" placeholder="Search my polls...">
        <button  class="search__btn">Search</button>
        <!-- Clear Filter Button -->
        <button class="clear-filter__btn">Clear Filter</button>
    </div>
    <br>
    <!-- Display Polls -->
        {% for poll in user.polls %}
        <div class="whole-poll">
            <div class="information">
                <h3><strong>{{ poll.title }}</strong></h3>
                <h4>{{ poll.description }}</h4>
            </div>
            
            <div class="poll">
                <div class="question">
                    {{ poll.question }}
                    <button type="button" class="close" onclick="deletePoll('{{ poll.id }}')">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
                <div class="answers">
                    <div class="answer" name="option_1" id="answer-0">
                        {{ poll.option_1 }}
                        <span class="percentage_bar"></span>
                        <span class="percentage_value"></span>
                    </div>
                    <div class="answer" name="option_2" id="answer-1">
                        {{ poll.option_2 }}
                        <span class="percentage_bar"></span>
                        <span class="percentage_value"></span>
                    </div>
                    {% if poll.option_3 %}
                    <div class="answer" name="option_3" id="answer-2">
                        {{ poll.option_3 }}
                        <span class="percentage_bar"></span>
                        <span class="percentage_value"></span>
                    </div>
                    {% endif %}
                    {% if poll.option_4 %}
                    <div class="answer" name="option_4" id="answer-3">
                        {{ poll.option_4 }}
                        <span class="percentage_bar"></span>
                        <span class="percentage_value"></span>
                    </div>
                    {% endif %}
                </div>
                <div class="poll-info">
                    <p>Total Votes: 0</p>
                </div>  
            </div>
        </div>
        {% endfor %}
</section>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
       <label for="email">Email Address</label> 
        <input 
            class="form-control"
            type="email" 
            name="email" 
            id="email" 
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input 
            type="password" 
            class="form-control"
            name="password" 
            id="password"
            placeholder="Enter password"
        >
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>  
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
       <label for="email">Email Address</label> 
        <input 
            class="form-control"
            type="email" 
            name="email" 
            id="email" 
            placeholder="Enter email"
        />
    </div>
    <div class="form-group">
        <label for="userName">User Name</label>
        <input 
            type="text" 
            class="form-control"
            name="userName" 
            id="userName"
            placeholder="Enter your user name"
        >
    </div> 
    <div class="form-group">
        <label for="password1">Password</label>
        <input 
            type="password" 
            class="form-control"
            name="password1" 
            id="password1"
            placeholder="Enter password"
        >
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input 
            type="password" 
            class="form-control"
            name="password2" 
            id="password2"
            placeholder="Confirm password"
        >
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>  
</form>
{% endblock %}

website/templates/vote.html
{% extends "base.html" %}
{% block title %}Vote Polls{% endblock %}

{% block content %}
<!-- Search Bar -->

<div class="search-bar">
    <input type="text" class="search-input" id="pollSearch" placeholder="Search my polls...">
    <button  class="search__btn">Search</button>
    <!-- Clear Filter Button -->
    <button class="clear-filter__btn">Clear Filter</button>
</div>
<br>

<!-- All Polls -->
{% for poll in polls %}
<div class="whole-poll">
    <div class="information">
        <h3><strong>{{ poll.title }}</strong></h3>
        <h4>{{ poll.description }}</h4>
    </div>
    <div class="poll">
        
        <div class="question">
            {{ poll.question }}
        </div>
        
        <div class="answers">
            <div class="answer" name="option_1" id="answer-0">
                {{ poll.option_1 }}
                <span class="percentage_bar"></span>
                <span class="percentage_value"></span>
            </div>
            <div class="answer" name="option_2" id="answer-1">
                {{ poll.option_2 }}
                <span class="percentage_bar"></span>
                <span class="percentage_value"></span>
            </div>
            {% if poll.option_3 %}
            <div class="answer" name="option_3" id="answer-2">
                {{ poll.option_3 }}
                <span class="percentage_bar"></span>
                <span class="percentage_value"></span>
            </div>
            {% endif %}
            {% if poll.option_4 %}
            <div class="answer" name="option_4" id="answer-3">
                {{ poll.option_4 }}
                <span class="percentage_bar"></span>
                <span class="percentage_value"></span>
            </div>
            {% endif %}
        </div>
        <div class="poll-info">
            <p>Creator: {{ user_names[poll.id] }}</p>
            <p>Total Votes: </p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock%}